---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.4
  - name: debian-6.0.8
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list: ["recipe[mlocate]"]
    attributes:
